//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remont
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка1()
        {
            this.Отчёт = new HashSet<Отчёт>();
        }
    
        public int Код_заявки { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Код_оргтехники { get; set; }
        public string Описание { get; set; }
        public Nullable<int> Код_пользователя { get; set; }
        public string ФИО_клиента { get; set; }
        public string Телефон { get; set; }
        public Nullable<int> Код_статуса { get; set; }
        public Nullable<int> Код_мастера { get; set; }
        public string Номер_заявки { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Оргтехника Оргтехника { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Статус Статус { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отчёт> Отчёт { get; set; }
    }
}
